spring:
  profiles:
    active: dev
  application:
    name: my-demo-boot
  cloud:
    aws:
      credentials:
        access-key: <your-access-key>
        secret-key: <your-secret-key>
        profile:
          name: default
      region:
        static: us-east-2
  config:
    import:
      # - aws-parameterstore:/config/${spring.application.name}_${spring.profiles.active}
      - aws-parameterstore:/config/my-demo-boot_default/
